# This is a basic workflow to help you get started with Actions

name: Create .upmconfig.toml UPM authentication file

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Create .upmconfig.toml UPM authentication file
        run: |
          mkdir /home/runner/work/_temp/_github_home
          cd /home/runner/work/_temp/_github_home
          echo "[npmAuth.\"https://upm.example.com\"]" >> .upmconfig.toml
          echo "alwaysAuth = true" >> .upmconfig.toml
          echo "token = \"${{ secrets.NPM_TOKEN }}\"" >> .upmconfig.toml
